version: '3.8'

services:
  db:
    env_file:
      - symfony/.env
    container_name: db
    image: postgres:16
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: dbtest
    ports:
        - 15432:5432

  php-fpm:
    env_file:
      - symfony/.env
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./symfony/:/var/www

  nginx:
    env_file:
      - symfony/.env
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./symfony/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs/nginx:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


